catalog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static 

app_name = "catalog"

urlpatterns = [
    path('', views.index, name='index'),

    path('collections/<str:catagory>', views.collections_catagory, name="collections_catagory"),
    path('collections/<str:catagory>/<str:name>', views.product_detail, name='product_detail'),

    path('cart/', views.cart, name='cart'),
    path('products/', views.QuestionListView.as_view(), name="product-list"),
    
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update-cart/<int:item_id>/<int:new_quantity>/', views.update_cart, name='update_cart'),
    path('remove-from-cart/<int:order_item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kescon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authentication.urls')),
    path('',include('catalog.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from authentication.models import Customer
from ckeditor.fields import RichTextField


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = RichTextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE) 
    brand = models.CharField(max_length=100, null=True, blank=True)
    images=models.ImageField(null=True, upload_to ='product_images/')
    stock_quantity = models.PositiveIntegerField(default=0)
    # on_sale = models.BooleanField(default=False) 
    
    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url=self.image.url
        except:
            url=''
        return url


class Order(models.Model):
    PENDING = 'Pending'
    PROCESSING = 'Processing'
    SHIPPED = 'Shipped'
    DELIVERED = 'Delivered'
    CANCELLED = 'Cancelled'
    
    STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (PROCESSING, 'Processing'),
        (SHIPPED, 'Shipped'),
        (DELIVERED, 'Delivered'),
        (CANCELLED, 'Cancelled'),
    ]

    customer=models.ForeignKey(Customer, on_delete=models.SET_NULL,null=True,blank=True)
    # complete=models.BooleanField(default=False)
    transaction_id=models.CharField(max_length=100,null=False)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=PENDING)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id )

    @property  
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping 


    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total=sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total=sum([item.quantity for item in orderitems])
        return total        


class OrderItem(models.Model):
    order= models.ForeignKey(Order, on_delete=models.SET_NULL,null=True)
    product=models.ForeignKey(Product, on_delete=models.SET_NULL,null=True)
    quantity=models.IntegerField(default=0,null=True, blank=True)
    date_added=models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total=self.product.price * self.quantity
        return total
    

    def __str__(self):
        return f"{self.quantity} x {self.product.name} ({self.product.price} each)"


class ShippingAddress(models.Model):
    customer=models.ForeignKey(Customer, on_delete=models.SET_NULL,null=True)
    order= models.ForeignKey(Order, on_delete=models.SET_NULL,null=True)
    address=models.CharField(max_length=200,null=False)
    city=models.CharField(max_length=200,null=False)
    state=models.CharField(max_length=200,null=False)
    zipcode=models.CharField(max_length=200,null=False)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

catalog/views.py
from django.shortcuts import render, redirect
from .models import *
import json
import datetime
from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from django.http import JsonResponse
import datetime
from . utils import cookieCart, cartData, guestOrder


def index(request):
    collection_products = Product.objects.all()[:8]
    special_products = Product.objects.all()[:4]
    special_products = Product.objects.all()[0:4]
    top_products = Product.objects.all()[7:10]
    best_selling_products = Product.objects.all()[10:13]
    customer = Customer.objects.all()
    if request.user.is_anonymous:
        order = None
    else:
        try:
            order = Order.objects.get(customer=request.user.customer)
        except Order.DoesNotExist:
            order = None
    context = {
        'collection_products': collection_products,
        'special_products': special_products,
        'top_products': top_products,
        'order': order,
        'best_selling_products': best_selling_products 
        }

    return render(request, 'index.html', context )


def collections_catagory(request, catagory):
    catagory = catagory.replace("_"," ")
    category = get_object_or_404(Category, name=catagory)
    products = Product.objects.filter(category=category)
    if request.user.is_anonymous:
        order = None
    else:
        try:
            order = Order.objects.get(customer=request.user.customer)
        except Order.DoesNotExist:
            order = None
    context = {'order': order,"products": products, "catagory": catagory }
    return render(request, 'collection.html',context )
    

def product_detail(request, name, catagory):
    product = Product.objects.get(name=name)
    if request.user.is_anonymous:
        order = None
    else:
        try:
            order = Order.objects.get(customer=request.user.customer)
        except Order.DoesNotExist:
            order = None
    context = {'order': order,'product':product}
    return render(request, 'product-detail.html', context)


def add_to_cart(request, product_id):
    if request.user.is_anonymous:
        return redirect('catalog:index')
    quantity = int(request.POST.get('quantity', 1))
    product = Product.objects.get(id=product_id)
    order, created = Order.objects.get_or_create(customer=request.user.customer)
    order_item, created = OrderItem.objects.get_or_create(order=order, product=product)
    order_item.quantity += quantity
    order_item.save()
    referer = request.META.get('HTTP_REFERER')

    if referer:
        return redirect(referer)
    else:
        return redirect('catalog:cart')


def remove_from_cart(request, order_item_id):
    order_item = OrderItem.objects.get(id=order_item_id)
    order_item.delete()
    return redirect('catalog:cart')


def cart(request):
    if request.user.is_anonymous:
        return redirect('catalog:index')
    Data=cartData(request)
    cartItems=Data['cartItems']
    order=Data['order']
    items=Data['items']
    
    context={'items':items, 'order': order,'cartItems':cartItems}
    return render (request,'cart.html',context)


def update_cart(request, item_id, new_quantity):
    try:
        order_item = OrderItem.objects.get(id=item_id)
        order_item.quantity = new_quantity
        order_item.save()

        return JsonResponse({'success': True})
    except OrderItem.DoesNotExist:
        return JsonResponse({'success': False, 'error': 'Item not found'})

class QuestionListView(ListView):
    model = Product
    context_object_name = 'search_products'
    template_name = "product_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_input = self.request.GET.get('search-area') or ""

        if not self.request.user.is_anonymous:
            order = Order.objects.get(customer=self.request.user.customer)
        else:
            order = None

        if self.request.user.is_anonymous:
            order = None
        else:
            try:
                order = Order.objects.get(customer=self.request.user.customer)
            except Order.DoesNotExist:
                order = None

        if search_input:
            context['search_products'] = context['search_products'].filter(name__icontains = search_input)
            context["search_input"] = search_input
        context['order'] = order
        return context

catalog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kescon</title>
    
    <link rel="shortcut icon" href="{% static 'images/KesconLogo.png'%}" type="image/x-icon">
    <!-- fontawesome cdn -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    <!-- <link rel = "stylesheet" href = "{% static "bootstrap-5.0.2-dist/css/bootstrap.min.css" %}"> -->
    <!-- custom css -->
    <link rel = "stylesheet" href = "{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'register.css' %}">
    <link rel = "stylesheet" href = "{% static 'css/cart.css' %}">
    <link rel = "stylesheet" href = "{% static 'css/product_style.css' %}">
</head>
<body>

    <!-- navbar -->
    <nav class = "navbar navbar-expand-lg navbar-light bg-white py-4 fixed-top">
        <div class = "container">
            <a class = "navbar-brand d-flex justify-content-between align-items-center order-lg-0" href = "{% url "catalog:index" %}">
                <img src = "{% static "images/KesconLogo.png" %}" alt = "site icon">
            </a>

            <div class = "order-lg-2 nav-btns">
                {% if request.user.is_authenticated %}
                <button type = "button" class = "btn position-relative">
                    <a href="{% url "catalog:cart" %}"><i class = "fa fa-shopping-cart"></i></a>
                    <span class = "position-absolute top-0 start-100 translate-middle badge bg-primary" id="cartItemCount">{{order.get_cart_items}}</span>
                </button>   

                <button type = "button" class = "btn position-relative">
                    <a href="{% url "profile" %}"><i class = "fa fa-user"></i></a>
                </button>
                {% else %}
                <button type = "button" class = "btn position-relative" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                   <i class = "fa fa-shopping-cart"></i>
                </button>
                <!-- Modal -->
                <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">Login</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        You are not signed in.
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <a href="{% url "login" %}">
                            <button type = "button" class = "login-btn position-relative">
                                Login
                            </button></a>
                      </div>
                    </div>
                  </div>
                </div>

                <a href="{% url "login" %}">
                <button type = "button" class = "login-btn position-relative">
                    Login
                </button></a>
                {% endif %}
            </div>

            <div class="search-form-box">
                <div class="px-2 py-2" style="text-align: center;" >
                    <div class="search-form-container" >
                        <form action="{% url "catalog:product-list" %}" method="GET">
                            <input type="text" id="" name="search-area"  placeholder="Search...">
                            <button type = "submit" class = "position-relative" style="border: none; background: none;">
                                <i class = "fa fa-search"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    {% block content %}



    {% endblock content %}

    <!-- footer -->
    <footer class = "bg-dark py-5">
      <div class = "container">
          <div class = "row text-white g-4">    

              <div class = "col-md-6 col-lg-3">
                  <h5 class = "fw-light">Links</h5>
                  <ul class = "list-unstyled">
                      <li class = "my-3">
                          <a href = "#" class = "text-white text-decoration-none text-muted">
                              <i class = "fas fa-chevron-right me-1"></i> Home
                          </a>
                      </li>
                      <li class = "my-3">
                          <a href = "#" class = "text-white text-decoration-none text-muted">
                              <i class = "fas fa-chevron-right me-1"></i> Collection
                          </a>
                      </li>
                      <li class = "my-3">
                          <a href = "#" class = "text-white text-decoration-none text-muted">
                              <i class = "fas fa-chevron-right me-1"></i> About Us
                          </a>
                      </li>
                  </ul>
              </div>

              <div class = "col-md-6 col-lg-3">
                  <h5 class = "fw-light mb-3">Contact Us</h5>
                  <div class = "d-flex justify-content-start align-items-start my-2 text-muted">
                      <span class = "me-3">
                          <i class = "fas fa-map-marked-alt"></i>
                      </span>
                      <span class = "fw-light">
                          Street, State, Country
                      </span>
                  </div>
                  <div class = "d-flex justify-content-start align-items-start my-2 text-muted">
                      <span class = "me-3">
                          <i class = "fas fa-envelope"></i>
                      </span>
                      <span class = "fw-light">
                          email@gmail.com
                      </span>
                  </div>
                  <div class = "d-flex justify-content-start align-items-start my-2 text-muted">
                      <span class = "me-3">
                          <i class = "fas fa-phone-alt"></i>
                      </span>
                      <span class = "fw-light">
                          +91 1234567890
                      </span>
                  </div>
              </div>

              <div class = "col-md-6 col-lg-3">
                  <h5 class = "fw-light mb-3">Follow Us</h5>
                  <div>
                      <ul class = "list-unstyled d-flex">
                          <li>
                              <a href = "#" class = "text-white text-decoration-none text-muted fs-4 me-4">
                                  <i class = "fab fa-facebook-f"></i>
                              </a>
                          </li>
                          <li>
                              <a href = "#" class = "text-white text-decoration-none text-muted fs-4 me-4">
                                  <i class = "fab fa-twitter"></i>
                              </a>
                          </li>
                          <li>
                              <a href = "#" class = "text-white text-decoration-none text-muted fs-4 me-4">
                                  <i class = "fab fa-instagram"></i>
                              </a>
                          </li>
                          <li>
                              <a href = "#" class = "text-white text-decoration-none text-muted fs-4 me-4">
                                  <i class = "fab fa-linkedin"></i>
                              </a>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>
      </div>
  </footer>
  <!-- end of footer -->


  <!-- jquery -->
  <!-- <script src = "{% static "js/jquery-3.6.0.js" %}"></script> -->
  <!-- bootstrap js -->
  <!-- <script src = "{% static "bootstrap-5.0.2-dist/js/bootstrap.min.js" %}"></script> -->

</body>
</html>

catalog/templates/collection.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- special products -->
<section id = "special" class = "py-5">
  <div class = "container">
      <div class = "title py-5" style="text-align: center;">
          <h2 class = "position-relative d-inline-block">{{catagory}} Collections</h2>
      </div>

      <div class = "special-list row g-0">
        {% for product in products  %}
          <div class = "col-md-6 col-lg-4 col-xl-3 p-2" style=" box-shadow: 0 0 20px 0 #eee;">
            <a href="{% url "catalog:product_detail" catagory=product.category.name name=product.name %}">
              <div class = "special-img position-relative overflow-hidden">
                  <img src = "{{product.images.url}}" class = "w-100" style="height: 310px;     object-fit: contain;">
                  <span class = "position-absolute d-flex align-items-center justify-content-center text-primary fs-4">
                      <i class = "fas fa-heart"></i>
                  </span>
              </div>
              <div class = "text-center">
                  <p class = "text-capitalize mt-3 mb-1">{{product.name}}</p>
                  <span class = "fw-bold d-block">Rs. {{product.price}}</span>

                  {% if request.user.is_authenticated %}
                  <a href = "{% url "catalog:add_to_cart" product.id %}" class = "btn btn-primary" style="width: max-content; align-self:center;">Add to Cart</a>
                  {% else %}
                  <a href = "{% url "catalog:add_to_cart" product.id %}"  data-bs-toggle="modal" data-bs-target="#staticBackdrop" class = "btn btn-primary" style="width: max-content; align-self:center;">Add to Cart</a>
                    <!-- Modal -->
                    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="staticBackdropLabel">Login</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                            You are not signed in.
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <a href="{% url "login" %}">
                                <button type = "button" class = "login-btn position-relative">
                                    Login
                                </button></a>
                          </div>
                        </div>
                      </div>
                    </div>
                  {% endif %}
          </div>
            </a>
          </div>
        {% endfor %}
      </div>

  </div>
</section>
<!-- end of special products -->

  {% endblock content %}

catalog/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}


    <!-- header -->
    <header id = "header" class = "carousel slide" data-bs-ride = "carousel">
        <div class="banner">
            <img src={% static "images/main_banner.webp" %} alt="">    
        </div>
    </header>
    <!-- end of header -->

    <!-- collection -->
    <section id = "collection" class = "py-5">
        <div class = "container">
            <div class = "title" style="text-align: center;">
                <h2 class = "position-relative d-inline-block">Our Collection</h2>
            </div>

            <div class = "row g-0">
                <div class = "d-flex flex-wrap justify-content-center mt-5 filter-button-group">
                    <a href="{% url "catalog:collections_catagory" "Office_Essentials" %}"><button type = "button" class = "btn m-2 text-dark" data-filter = ".best">Office Essentials</button></a>
                    <a href="{% url "catalog:collections_catagory" "Stationary" %}"><button type = "button" class = "btn m-2 text-dark" data-filter = ".feat">Staionary</button></a>
                    <a href="{% url "catalog:collections_catagory" "Bussiness_items" %}"><button type = "button" class = "btn m-2 text-dark" data-filter = ".new">Bussiness items</button></a>
                </div>

                <div class = "collection-list mt-4 row gx-0 gy-3">

                  {% for product in collection_products %}
                  <div class = "col-md-6 col-lg-4 col-xl-3 p-2 best" style=" box-shadow: 0 0 20px 0 #eee;">
                      <a href="{% url "catalog:product_detail" product.category.name product.name %}">
                        <div class = "collection-img position-relative">
                            <img src = "{{ product.images.url }}" class = "w-100" style="height: 310px;     object-fit: contain;" >
                            <span class = "position-absolute bg-primary text-white d-flex align-items-center justify-content-center">sale</span>
                        </div>
                        <div class = "text-center" >
                            <div class = "rating mt-3">
                                <span class = "text-primary"><i class = "fas fa-star"></i></span>
                                <span class = "text-primary"><i class = "fas fa-star"></i></span>
                                <span class = "text-primary"><i class = "fas fa-star"></i></span>
                                <span class = "text-primary"><i class = "fas fa-star"></i></span>
                                <span class = "text-primary"><i class = "fas fa-star"></i></span>
                            </div>
                            <p class = "text-capitalize my-1">{{product.name}}</p>
                            <span class = "fw-bold">Rs. {{product.price}}</span>
                        </div>
                      </a>
                    </div>
                  {% endfor %}

                </div>
            </div>
        </div>
    </section>
    <!-- end of collection -->

    <!-- special products -->
    <section id = "special" class = "py-5">
        <div class = "container">
            <div class = "title py-5" style="text-align: center;">
                <h2 class = "position-relative d-inline-block">Special Selection</h2>
            </div>

            <div class = "special-list row g-0">

              {% for product in special_products  %}
                <div class = "col-md-6 col-lg-4 col-xl-3 p-2" style=" box-shadow: 0 0 20px 0 #eee;">
                  <a href="{% url "catalog:product_detail" catagory=product.category.name name=product.name %}">
                    <div class = "special-img position-relative overflow-hidden">
                        <img src = "{{product.images.url}}" class = "w-100" style="height: 310px;     object-fit: contain;">
                        <span class = "position-absolute d-flex align-items-center justify-content-center text-primary fs-4">
                            <i class = "fas fa-heart"></i>
                        </span>
                    </div>
                    <div class = "text-center">
                        <p class = "text-capitalize mt-3 mb-1">{{product.name}}</p>
                        <span class = "fw-bold d-block">Rs. {{product.price}}</span>

                        {% if request.user.is_authenticated %}
                        <a href = "{% url "catalog:add_to_cart" product.id %}" class = "btn btn-primary" style="width: max-content; align-self:center;">Add to Cart</a>
                        {% else %}
                        <a href = "{% url "catalog:add_to_cart" product.id %}"  data-bs-toggle="modal" data-bs-target="#staticBackdrop" class = "btn btn-primary" style="width: max-content; align-self:center;">Add to Cart</a>
                         <!-- Modal -->
                         <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                           <div class="modal-dialog">
                             <div class="modal-content">
                               <div class="modal-header">
                                 <h5 class="modal-title" id="staticBackdropLabel">Login</h5>
                                 <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                               </div>
                               <div class="modal-body">
                                 You are not signed in.
                               </div>
                               <div class="modal-footer">
                                 <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                 <!-- <button type="button" class="btn btn-primary">Login</button> -->
                                 <a href="{% url "login" %}">
                                     <button type = "button" class = "login-btn position-relative">
                                         Login
                                     </button></a>
                               </div>
                             </div>
                           </div>
                         </div>
                        {% endif %}
                    </div>
                  </a>
                </div>
              {% endfor %}

            </div>
        </div>
    </section>
    <!-- end of special products -->

    <!-- popular -->
    <section id = "popular" class = "py-5">
        <div class = "container">
            <div class = "title  pt-3 pb-5" style="text-align: center;">
                <h2 class = "position-relative d-inline-block ms-4">Popular Of This Year</h2>
            </div>

            <div class = "row">
                <div class = "col-md-6 col-lg-6 row g-3">
                    <h3 class = "fs-5"><strong>Top Rated</strong></h3>

                    {% for product in top_products %}
                      <div class = "d-flex align-items-start justify-content-start">
                        <a href="{% url "catalog:product_detail" catagory=product.category.name name=product.name %}">
                            <img src = "{{product.images.url}}" alt = "" class = "img-fluid pe-3 w-100" style="max-width: 160px; height: 150px; object-fit: contain;">
                        <div >
                              <p class = "mb-0">{{product.name}}</p>
                              <span>Rs. {{product.price}}</span>
                          </div>
                        </a>
                      </div>
                    {% endfor %}

                </div>

                <div class = "col-md-6 col-lg-6 row g-3">
                    <h3 class = "fs-5"> <strong>Best Selling</strong></h3>

                    {% for product in best_selling_products  %}
                    <div class = "d-flex align-items-start justify-content-start" >
                        <a href="{% url "catalog:product_detail" catagory=product.category.name name=product.name %}">
                            <img src = "{{product.images.url}}" alt = "" class = "img-fluid pe-3 w-100" style="max-width: 160px; height: 150px; object-fit: contain;">
                        <div>
                            <p class = "mb-0">{{product.name}}</p>
                            <span>Rs. {{product.price}}</span>
                        </div>
                      </a>
                    </div>
                    {% endfor %}

                </div>

            </div>
        </div>
    </section>
    <!-- end of popular -->

    <!-- newsletter -->
    <section id = "newsletter" class = "py-5">
        <div class = "container">
            <div class = "d-flex flex-column align-items-center justify-content-center">
                <div class = "title pt-3 pb-5" style="text-align: center;">
                    <h2 class = "position-relative d-inline-block ms-4">Reach Out to Us</h2>
                </div>

                <div class = "input-group mb-3 mt-3">
                    <input type = "text" class = "form-control" placeholder="Enter Your Email ...">
                    <button class = "btn btn-primary" type = "submit">Contact</button>
                </div>
            </div>
        </div>
    </section>
    <!-- end of newsletter -->

{% endblock content %}